In [1]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [2]:
########################################################################################################
#Ans 01:

In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

In [5]:
########################################################################################################
#Ans 02:

In [6]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [7]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [8]:
########################################################################################################
#Ans 03:

In [9]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [10]:
array_list = np.array(object = list_, dtype = int)

In [11]:
array_list

array([1, 2, 3, 4, 5])

In [12]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [13]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [14]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [15]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
########################################################################################################
#Ans 04:

In [17]:
num_array.shape

(2, 3)

In [18]:
num_array.size

6

In [19]:
########################################################################################################
#Ans 05:

In [20]:
arr1 = np.zeros((3,3))

In [21]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
########################################################################################################
#Ans 06:

In [23]:
arr2 = np.eye(5)

In [24]:
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
########################################################################################################